### PR TITLE
fix closenow race

### PR DESCRIPTION
**Pull request by alixander**
the added test fails before this with

Screen Shot 2023-12-18 at 3 32 16 PM

------------

i originally found this in D2 when i added tests for watching and --race started failing but the code seems to be purely confined in this library.

Screen Shot 2023-12-18 at 3 35 58 PM

------

hacked together test, so if you accept it and want me to clean it up, i can. just seeing if this is legit.

### CODE REVIEW

**Comment by nhooyr** [comment]
Copy, weird. Will review tonight. Have a Christmas party now. Happy Holidays! 🥳

**Comment by nhooyr** [comment]
Didn't get a chance, hopefully tomorrow.

**Comment by nhooyr** [comment]
I despise the way this code was implemented. This is one of multiple races. See also #239 

But this looks like the right fix thanks @alixander 

I'll take a look at the test tonight. Helping cook Christmas meals at the Legion today.

**Comment by alixander** [comment]
Merry Christmas man! Christmas in small towns sound 💯 .

I'm sure the test isn't up to par lol. Happy to address comments but also if you wanna just push to this or redo this in another PR, I'm cool with it.

**Comment by ClaytonNorthey92** [comment]
hey @alixander and @nhooyr , is it possible to merge this fix in? I am running into this issue on one of my projects.

thanks!

**Comment by nhooyr** [comment]
I know it's on my radar.

**Comment by nhooyr** [comment]
Will have a release out by Sunday to fix this and all the associated bugs.

**Comment by nhooyr** [comment]
Not sure why the Wasm test is failing, looking into it. Not sure if it's related to this PR or something else as it seems to fail intermittently in the daily CI.

**Pull request merged**
