### PR TITLE
Avoid handling ping after close frame has been sent

### PR DESCRIPTION
**Pull request by bhallionOhbibi**
Fixes https://github.com/nhooyr/websocket/issues/298

### CODE REVIEW

**Comment by bhallionOhbibi** [comment]
Any chance you have time to take a quick look at this ?
This fix is quite simple :D

**Comment by nhooyr** [comment]
Unfortunately this doesn't work. writeFrame already has a check like this built in so it makes sense it doesn't work. There is definitely a bug in #298, but need to dig deeper to figure out what.

See the test I added to your commit, it still fails.

**Comment by nhooyr** [comment]
See https://github.com/nhooyr/websocket/commit/e4879ab74e5dd045a4ef5707f2c542b9cf4a4321 for the test

**Comment by nhooyr** [comment]
Fixed in dev, see https://github.com/nhooyr/websocket/commit/28c670953e8a6c6ecf147f89ac0085ac6510999e

**Pull request closed without merging**
