### PR TITLE
Refactoring

### LINKED ISSUE #78: Improve Close UX
https://www.reddit.com/r/golang/comments/bi2tan/nhooyrwebsocket_a_minimal_and_idiomatic_websocket/em1jn6d/?context=3

The close only happens for the first call.

Also, instead of returning an error when the close code/reason are invalid, we should just print to stderr like net/http as no one will ever check Close's error, in normal usage anyway.

### PR DESCRIPTION
**Pull request by nhooyr**
Closes #78

### CODE REVIEW

**Comment by nhooyr** [comment]
This PR adds concurrent reads and massively simplifies the internals of the libraries 👏

**Comment by nhooyr** [comment]
Figured out a clever way to merge readLoop and timeoutLoop into a single goroutine!

**Comment by nhooyr** [comment]
Nvm I did not, I thought io.Reader was non blocking but it isn't. It blocks for at least a single read usually. So if we combine the two, then there is no way to get readLoop to wake up.

**Comment by nhooyr** [comment]
@coadler Definitely let me know how you feel about the additions to the API.

**Comment by coadler** [comment]
:+1: will take a look tomorrow morning

**Comment by coadler** [comment]
I'll test these out on my gateway later this weekend and let you know anything else I find

**Pull request merged**
