### PR TITLE
Update dependencies to latest versions

### PR DESCRIPTION
**Pull request by Jacalz**
This modernizes the imported packages a lot by updating to the latest releases. It should bring many improvements and a fix for https://github.com/nhooyr/websocket/issues/318. The protobuf package should probably be updated to "google.golang.org/protobuf/proto" but this is at least better than before.

### CODE REVIEW

**Comment by ohaeusler** [comment]
Thank you @Jacalz I've forked your fork and created a release for myself, which im using until @nhooyr answers.

**Comment by Jacalz** [comment]
@nhooyr Any chance that you'd be able to review this?

**Comment by ryanchristo** [comment]
Any updates on this? Mainly concerned about https://github.com/advisories/GHSA-h395-qcrw-5vmq.

**Comment by Jacalz** [comment]
Until this repository is maintained, I will continue to update the dependencies in https://github.com/rymdport/websocket. However, I have enough on my plate already and can not guarantee any bug fixes or features being implemented from my side.

**Comment by nhooyr** [comment]
I cannot merge this in due to other pending changes. I'm going to be removing all of these dependencies from the test code and move the tests that use them into a separate module. See #297

**Comment by nhooyr** [comment]
Though thank you for your work @Jacalz and sorry I've been unresponsive.

**Comment by Jacalz** [comment]
@nhooyr It's great to see you being active again. I'll go ahead  and delete my fork once you have implemented those changes (and has the project entirely up and running again) :)

**Pull request closed without merging**
