### PR TITLE
github.com/gin-gonic/gin version bump

### PR DESCRIPTION
**Pull request by sdrobov**
Dependabot alerts, that github.com/gin-gonic/gin < 1.7.0 has critical vulnerability, so I bumped version to latest atm.

### CODE REVIEW

**Comment by srt32** [comment]
FWIW, the dep is used only in tests as far as I can tell.

**Comment by sdrobov** [comment]
All the more reason to update

**Comment by JoseInTheArena** [comment]
Hi @nhooyr! Any chance you could take a look at this?

**Comment by schmigware** [comment]
Would be great if this PR were merged.

**Review by glaslos — APPROVED** [review]
LGTM

**Pull request closed without merging**
